<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>pilz_robot_programming</name>
  <version>0.5.0</version>
  <description>Easy-to-use Python API for Pilz industrial robot commands (Ptp, Lin, Circ, Sequence) using MoveIt2.</description>
  <maintainer email="ros-student@todo.todo">ros-student</maintainer>
  <license>LGPL-3.0-only</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>ament_cmake_python</buildtool_depend>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>moveit_msgs</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>shape_msgs</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>std_srvs</exec_depend>
  <exec_depend>control_msgs</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>trajectory_msgs</exec_depend>
  <exec_depend>tf2_ros_py</exec_depend>
  <exec_depend>tf2_geometry_msgs</exec_depend>
  <exec_depend>tf_transformations</exec_depend>
  <exec_depend>pilz_msgs</exec_depend>
  <exec_depend>pilz_industrial_motion_planner</exec_depend>

  <depend>python3-psutil</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
