<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>prbt_moveit_config</name>
  <version>0.6.0</version>
  <description>MoveIt2 configuration for the Pilz PRBT robot</description>
  <maintainer email="ros-student@todo.todo">ros-student</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>joint_state_publisher</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>xacro</exec_depend>

  <depend>moveit_ros_move_group</depend>
  <depend>moveit_kinematics</depend>
  <depend>moveit_planners_ompl</depend>
  <depend>moveit_ros_visualization</depend>
  <depend>moveit_simple_controller_manager</depend>
  <depend>pilz_industrial_motion_planner</depend>
  <depend>controller_manager</depend>
  <depend>joint_state_broadcaster</depend>
  <depend>joint_trajectory_controller</depend>
  <depend>rviz2</depend>
  <depend>prbt_support</depend>
  <depend>prbt_pg70_support</depend>


  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
