<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>prbt_hardware_support</name>
  <version>0.6.0</version>
  <description>Hardware support package for Pilz PRBT - provides fake safety interface for simulation</description>
  <maintainer email="ros-student@todo.todo">ros-student</maintainer>
  <license>LGPL-3.0-only</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>pilz_msgs</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
