<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>pilz_tutorial</name>
  <version>0.0.0</version>
  <description>The pilz_tutorial package - ROS2 Jazzy version</description>
  <maintainer email="ros-student@todo.todo">ros-student</maintainer>
  <license>TODO</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>ament_cmake_python</buildtool_depend>

  <exec_depend>prbt_moveit_config</exec_depend>
  <exec_depend>prbt_support</exec_depend>
  <exec_depend>prbt_pg70_support</exec_depend>
  <exec_depend>prbt_hardware_support</exec_depend>
  <exec_depend>pilz_robot_programming</exec_depend>
  <exec_depend>xacro</exec_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
